INSERT INTO `stations` (`name`) VALUES
('Niquía'),
('Bello'),
('Madera'),
('Acevedo'),
('Tricentenario'),
('Caribe'),
('Universidad'),
('Hospital'),
('Prado'),
('Parque Berrío'),
('San Antonio'),
('Alpujarra'),
('Exposiciones'),
('Estadio'),
('Floresta'),
('Santa Lucía'),
('La Estrella'),
('San Javier'),
('Juan XXIII'),
('La Candelaria'),
('Andalucía'),
('Popular'),
('Cisneros'),
('Miraflores'),
('Patio Bonito');